# Generated by Django 2.2.3 on 2019-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('citydomain', models.CharField(max_length=2)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
